### ISSUE TITLE
Can I download your trained weights?

### ISSUE THREAD

**Issue by suoranxiu** [bodokaiser/mrtoct-pytorch#1]
Can I download your trained weights？I want to use your method to make preporocess. Thank you!

**Comment by bodokaiser** [comment]
Hi, I did got far with this project. You might want to try [mrtoct-tensorflow][1] though. You can find the training checkpoints for mrtoct-tensorflow [here][2].

That said, I would not recommend using any of my machine learning projects at this time. Tensorflow and pytorch have evolved quite a bit since 2018 and it may be quite some effort to get things back working.

[1]: https://github.com/bodokaiser/mrtoct-tensorflow
[2]: https://syncandshare.lrz.de/getlink/fi9WEtntBKU5GXbasykNuBrR/

**Comment by suoranxiu** [comment]
Thank you for your answer！And I will try it.
